export { default as IconUser } from "./User";
export { default as IconPatchQuestion } from "./PatchQuestion";
export { default as IconArrowUpSquare } from "./ArrowUpSquare";
export { default as IconSettingsOutline } from "./Settings";
export { default as IconHamburgerMenu } from "./HamburgerMenu";
export { default as IconCloseOutline } from "./Close";
export { default as IconSearch } from "./Search";
export { default as IconAngleLeft } from "./AngleLeft";
export { default as IconAngleRight } from "./AngleRight";
export { default as IconSpinner } from "./Spinner";
export { default as IconError } from "./ErrorOutline";
export { default as IconShare } from "./Share";
export { default as IconDownload } from "./Download";
export { default as IconShow } from "./Show";
export { default as IconLowVision } from "./LowVision";
export { default as IconHomeAlt } from "./HomeAlt";
export { default as IconStar } from "./Star";
export { default as IconStarFill } from "./StarFill";
export { default as IconSoup } from "./Soup";
export { default as IconCheck } from "./Check";
export { default as IconArrowLeftCircle } from "./ArrowLeftCircle";

export { IconYoutube } from "./Socials";
export { IconFacebook } from "./Socials";
export { IconInstagram } from "./Socials";
export { IconLinkedin } from "./Socials";
export { IconTwitter } from "./Socials";
export { IconGithub } from "./Socials";
export { IconBehanceCircle } from "./Socials";
